source 'https://rubygems.org'

gem 'awesome_print'
gem 'bcrypt'
gem 'coffee-rails'
gem 'compass-rails'
gem 'devise'
gem 'enumerize'
gem 'gravatar_image_tag'
gem 'jbuilder'
gem 'jquery-rails'
gem 'keynote', '~> 0.2.3'
gem 'jquery-turbolinks'
gem 'pg'
gem 'rails', '~> 4.1.7'
gem 'russian'
gem 'sass-rails'
gem 'simple_form'
gem 'slim'
gem 'slim-rails'
gem 'state_machine'
gem 'therubyracer',  platforms: :ruby
gem 'turbolinks'
gem 'uglifier'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'quiet_assets'
  gem 'rack-mini-profiler'
end

group :test, :development do
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'guard-rspec'
  gem 'rb-fsevent'
  gem 'rspec-collection_matchers'
  gem 'rspec-its'
  gem 'rspec-rails'
  gem 'shoulda'
  gem 'shoulda-matchers'
end
